config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  get 'charges/create'

  post 'products/search' => 'category#search', as: 'search_products'

  get '' => 'category#index', as: 'index'

  get '/:id' => 'category#show', as: 'show', id: /\d+/

  get '/product/:id' => 'product#show', as: 'show_product', id: /\d+/

  get '/cart'=> 'product#show_cart', as: 'cart'

  get 'products/change_quantity' => 'product#change_quantity'

  get '/checkout' => 'product#checkout', as: 'checkout'

  post '/checkout/new/customer' => 'customer#create', as: 'customers'

  get '/verify_order' => 'customer#verify_order', as: 'verify_order'

  get '/checkout/order' => 'customer#order', as: 'order'

  resources :charges

  resources :product, only: [:index] do
    member do
      post :remove_from_cart
      post :add_to_cart
    end
  end


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }

  validates :name, :price, :description, presence:true
  validates :name, :format => { :with => /\A[A-Za-z0-9\/\.\s]+\z/ }

  # Maximum of 2 decimal places.
  # Adapted from https://stackoverflow.com/a/38517312/5952715
  validates :price, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  before_action :set_categories
  before_action :initialize_session
  before_action :load_products_in_cart, only: [:show_cart, :checkout]

  def set_categories
    @categories = Category.includes(:products).all.order("name")
  end

  def show
    @product = Product.find(params[:id])
  end

  def show_cart

  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete("#{id}")

    product_name = Product.find(id).name
    redirect_to request.referer, notice: "Removed #{product_name} from the cart."
  end

  def add_to_cart
    # get product id
    id = params[:id].to_i
    # push product to session
    session[:cart].store("#{id}", 1) unless session[:cart].key?("#{id}")

    product_name = Product.find(id).name
    redirect_to request.referer, notice: "Added #{product_name} to the cart."
  end

  def change_quantity
    # get product id
    id = params[:id].to_i
    quantity = params[:quantity].to_i
    # update product quantity
    session[:cart]["#{id}"] = quantity
  end

  def checkout
    @provinces = Province.all.order("name")
  end

  private

  def initialize_session
    # if cart is not initialized
    session[:cart] ||= {}
  end

  def load_products_in_cart
    @products_in_cart = Product.find(session[:cart].keys)
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/checkout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <header>
    <h1>Checkout</h1>
  </header>
  <body>
    <p class = "checkout_main">
      <%= form_for(Customer.new) do |f| %>
      <div class = "form_field">
        <%= f.label :username %>
        <%= f.text_field :username %>
      </div>
      <div class = "form_field">
        <%= f.label :password %>
        <%= f.text_field :password %>
      </div>
      <div class = "form_field">
        <%= f.label :province_id %>
        <%= f.select :province_id, @provinces.map { |province| [ province.name, province.id ] } %>
      </div>
      <div class = "form_field">
        <%= f.label :address %>
        <%= f.text_field :address %>
      </div>

      <div class = "form_field">
      <%= f.label :postal %>
      <%= f.text_field :postal %>
      </div>
      <%= f.submit "Confirm Order" %>
      <%end%>
      </form>
      <div class="order_products">
        <h4>Products Ordered</h4>
        <% @products_in_cart.each do |product| %>
          <%= render 'products/order_product', :product => product %>
        <% end %>
        <p>Subtotal: <%= number_to_currency @products_in_cart.inject(0) { |subtotal, product| subtotal + (product.price * session[:cart]["#{product.id}"]) }%></p>
      </div>
      <div class="both"></div>
    </p>
  </body>
</html>

app/views/product/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <p>
      <div class="category">
        <h2><%=@product.name%></h2>
          <div class="product_detail">
            <p class="product_image">
              <%= image_tag(@product.image.url(:large)) unless @product.image.url.include? 'missing.png' %>
            </p>
            <p>Category: <%=@product.category.name%></p>
            <p><%=@product.description%></p>
            <p>Price: <%= number_to_currency(@product.price)%></p>
          </div>
      </div>
    </p>
  </body>
</html>

app/views/product/show_cart.html.erb
<script type="application/javascript">
  $(function() {
    $('input[name="quantity"]').change(function() {
        var quantity = this.value;
        $.ajax({
            url: 'products/change_quantity',
            data: 'id=' + this.parentElement.getElementsByTagName('input')[0].value + '&quantity=' + this.value,
            success: function() {
                alert("Quantity updated to " + quantity + ".");
            }
        });
    });
  });
</script>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <header>
    <h1>Shopping Cart</h1>
  </header>
  <body>
    <p>
      <% if @products_in_cart.any? %>
      <div class="category">
        <h4>Please wait between each quantity change for an alert to show up confirming the change.</h4>
        <% @products_in_cart.each do |product| %>
          <%= render 'products/cart_product', :product => product %>
        <% end %>
        <form id = "checkout">
          <%= link_to '<button type="button">Proceed to Checkout</button>'.html_safe, checkout_path %>
        </form>
      </div>
      <% else %>
        There are no products in your cart.
      <% end %>
    </p>
  </body>
</html>