config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  get 'charges/create'

  post 'products/search' => 'category#search', as: 'search_products'

  get '' => 'category#index', as: 'index'

  get '/:id' => 'category#show', as: 'show', id: /\d+/

  get '/product/:id' => 'product#show', as: 'show_product', id: /\d+/

  get '/cart'=> 'product#show_cart', as: 'cart'

  get 'products/change_quantity' => 'product#change_quantity'

  get '/checkout' => 'product#checkout', as: 'checkout'

  post '/checkout/new/customer' => 'customer#create', as: 'customers'

  get '/verify_order' => 'customer#verify_order', as: 'verify_order'

  get '/checkout/order' => 'customer#order', as: 'order'

  resources :charges

  resources :product, only: [:index] do
    member do
      post :remove_from_cart
      post :add_to_cart
    end
  end


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/common/_footer.html.erb
<p>Dan Ho</p>
<p><a href="mailto:vidanho@gmail.com">vidanho@gmail.com</a></p>
<p>2017</p>

app/views/common/_links.html.erb
<nav>
  <ul class = "navigation">
    <li><%= link_to 'Home', index_path %></li>
    <div class="dropdown">
      <div class="dropbtn">Categories</div>
      <div class="dropdown-content">
        <% @categories.each do |category| %>
            <%=link_to category.name, show_path(category.id)%>
        <%end%>
      </div>
    </div>
    <li><%= link_to 'Cart', cart_path %></li>
    <li><%= link_to 'ABoot', index_path %></li>
    <li><%= link_to 'Contact', index_path %></li>
    <%= render 'common/search', :categories => @categories %>
  </ul>
</nav>

app/views/common/_minicart.html.erb
<section class="minicart">
  <% if products_in_cart.any? %>
      <h3>Products In Cart</h3>
      <ul>
      <% products_in_cart.each do |product| %>
        <li><%= product.name %> <%= link_to "[x]", remove_from_cart_product_path(product), method: :post, class: "link_to_mini" %></li>
      <% end %>
      </ul>
  <% end %>
</section>

app/views/common/_products.erb
<div class="product">
  <h3><%= link_to product.name, show_product_path(product.id) %></h3>
  <p class="product_image">
    <% if product.image.url.include? 'missing.png' %>
      <%= link_to '[' + product.name + ']', show_product_path(product.id) %>
    <% else %>
      <%= link_to image_tag(product.image.url(:med)), show_product_path(product.id) %>
    <% end %>
  </p>
  <p>Price: $<%= product.price%></p>
  <%= link_to "Buy", add_to_cart_product_path(product), method: :post %>

</div>

app/views/common/_search.html.erb
<div class="navsearch">
  <%= form_tag search_products_path do %>
    <select name="search_category">
        <option value="-1">All</option>
      <% @categories.each do |category| %>
        <option value="<%=category.id%>"><%=category.name%></option>
      <% end %>
    </select>
    <input class="searchbar" id="searchbar" name="query" placeholder="Search Products" type="text" autocomplete="off"/>
    <button type="submit" formmethod="post">Search</button>
  <% end %>
</div>