config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  get 'charges/create'

  post 'products/search' => 'category#search', as: 'search_products'

  get '' => 'category#index', as: 'index'

  get '/:id' => 'category#show', as: 'show', id: /\d+/

  get '/product/:id' => 'product#show', as: 'show_product', id: /\d+/

  get '/cart'=> 'product#show_cart', as: 'cart'

  get 'products/change_quantity' => 'product#change_quantity'

  get '/checkout' => 'product#checkout', as: 'checkout'

  post '/checkout/new/customer' => 'customer#create', as: 'customers'

  get '/verify_order' => 'customer#verify_order', as: 'verify_order'

  get '/checkout/order' => 'customer#order', as: 'order'

  resources :charges

  resources :product, only: [:index] do
    member do
      post :remove_from_cart
      post :add_to_cart
    end
  end


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
  validates :username, :password, :province_id, presence: true
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  before_action :set_categories
  before_action :initialize_session
  before_action :load_products_in_cart, only: [:verify_order]

  def create
    username = params[:customer][:username]
    password = params[:customer][:password]
    province_id = params[:customer][:province_id]
    address = params[:customer][:address]
    postal = params[:customer][:postal]

    customer = Customer.create(username: username, password: password, province_id: province_id, postal: postal, address: address)
    customer.save

    redirect_to controller: 'customer', action: 'verify_order', id: customer.id
  end

  def verify_order
    @customer = Customer.find(params[:id])
    session[:id] = params[:id]
    @province = @customer.province

    @total_taxes = 1 + ((@province.gst_rate + @province.pst_rate + @province.hst_rate) / 100).to_f

    @grand_total = @products_in_cart.inject(0) { |total, product| total + (product.price.to_f * session[:cart]["#{product.id}"].to_f * @total_taxes) }
    session[:grand_total] = (@grand_total.to_f.round(2) * 100)
  end

  def order
    customer = Customer.find(params[:id])

    products = Product.find(session[:cart].keys)

    # Status = "Paid"
    order = Order.create(order_status_id: 2, customer_id: customer.id)
    order.save

    order_items = []
    products.each do |order_product|
      order_item = OrderItem.create(quantity: session[:cart]["#{order_product.id}"], product_id: order_product.id, order_id: order.id)
      order_item.save
      order_items.push(order_item)
    end

    flash[:notice] = "Order completed and logged. You paid $#{session[:grand_total] / 100.00}."
    redirect_to controller: 'product', action: 'show_cart'
  end

  private

  def initialize_session
    # if cart is not initialized
    session[:cart] ||= {}
  end

  def set_categories
    @categories = Category.includes(:products).all.order("name")
  end

  def load_products_in_cart
    @products_in_cart = Product.find(session[:cart].keys)
  end
end

app/views/customer/verify_order.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <header>
    <h1>Order</h1>
  </header>
  <body>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
    </article>
    <div class = "verify_main">
      <div class = "form_field">
        <%=@customer.username%>
      </div>
      <div class = "form_field">
        <%=@customer.province.name%>
      </div>
      <p>Subtotal: <%= number_to_currency @products_in_cart.inject(0) { |subtotal, product| subtotal + (product.price * session[:cart]["#{product.id}"]) }%></p>
      <% if @province.gst_rate > 0.0 %>
      <p>GST: <%= number_to_currency @products_in_cart.inject(0) { |gst, product| gst + (product.price * session[:cart]["#{product.id}"] * (@province.gst_rate / 100)) }%></p>
      <% end %>
      <% if @province.pst_rate > 0.0 %>
      <p>PST: <%= number_to_currency @products_in_cart.inject(0) { |pst, product| pst + (product.price * session[:cart]["#{product.id}"] * (@province.pst_rate / 100)) }%></p>
      <% end %>
      <% if @province.hst_rate > 0.0 %>
      <p>HST: <%= number_to_currency @products_in_cart.inject(0) { |hst, product| hst + (product.price * session[:cart]["#{product.id}"] * (@province.hst_rate / 100)) }%></p>
      <% end %>
      <p>Grand Total: <%= number_to_currency(@grand_total.to_f) %></p>
      <%= link_to "<button>Proceed to Payment</button>".html_safe, charges_new_path %>
    </div>
      <div class="order_products">
        <h4>Products Ordered</h4>
        <% @products_in_cart.each do |product| %>
          <%= render 'products/order_product', :product => product %>
          <% end %>
      </div>
      <div class="both"></div>
  </body>
</html>