config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  get 'charges/create'

  post 'products/search' => 'category#search', as: 'search_products'

  get '' => 'category#index', as: 'index'

  get '/:id' => 'category#show', as: 'show', id: /\d+/

  get '/product/:id' => 'product#show', as: 'show_product', id: /\d+/

  get '/cart'=> 'product#show_cart', as: 'cart'

  get 'products/change_quantity' => 'product#change_quantity'

  get '/checkout' => 'product#checkout', as: 'checkout'

  post '/checkout/new/customer' => 'customer#create', as: 'customers'

  get '/verify_order' => 'customer#verify_order', as: 'verify_order'

  get '/checkout/order' => 'customer#order', as: 'order'

  resources :charges

  resources :product, only: [:index] do
    member do
      post :remove_from_cart
      post :add_to_cart
    end
  end


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    before_action :set_categories
  def new
    @grand_total = session[:grand_total]
    @description = "Useful Gadgets Payment"
  end

  def create
    # Amount in cents
    amount = session[:grand_total]

    @customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    @charge = Stripe::Charge.create(
      :customer    => @customer.id,
      :amount      => amount.round(0),
      :description => 'Rails Stripe customer',
      :currency    => 'cad'
    )

    #Associate current customer with 3rd party Stripe customer
    customer = Customer.find(session[:id])
    customer.stripe_id = @customer.id
    customer.save

    if @charge.paid && @charge.amount == amount.round(0)
      redirect_to controller: 'customer', action: 'order', id: session[:id]
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to verify_order_path
  end

  private

  def set_categories
    @categories = Category.includes(:products).all.order("name")
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h2>An error occurred! Please try again.</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= number_to_currency(@grand_total / 100)%></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description=<%= @description %>
          data-amount=<%= @grand_total %>
          data-locale="auto"></script>
<% end %>